#ifndef UART_H_
#define UART_H_

#define UART_BAUD_RATE 9600.0

#define UART_NUM_DATA_BITS (8)

#define UART_STOP_BITS (1)

#define UART_NUM_BITS (1 + UART_NUM_DATA_BITS)

// RXD0 corresponds to PCINT24 pin, so any hardware change is needed.
inline void UART_init() {
	DDRD &= ~(1<<PD0);
	PCICR |= (1<<PCIE3);				//	Enable pin change interrupt on PCINT31:24 pins.
	PCMSK3 |= (1<<PCINT24);				//	Enable pin change interrupt PCINT24 pin.
	
	/*	Set PB2 (INT2 pin) as output to generate software interrupt, to move received bytes handling 
		on other level of application.														*/
	DDRB |= (1<<PB2);
	
	//	Set rising edge triggering software interrupt.
	EICRA |= (1<<ISC21) | (1<<ISC20);	
	
	//	Enable interrupt generated by INT2 pin.		
	EIMSK |= (1<<INT2);					
}

//	Timer 2 is used to count bits in frame.
inline void Timer2_init() {
	TCCR2A |= (1<<WGM21);				// CTC mode
	TCCR2B |= (1<<CS21);				// Prescaler F_CPU/8
	OCR2A = (uint8_t)(F_CPU / 8.0 / UART_BAUD_RATE - 0.5);			// 8000000/8/9600 - 1 = 104,1(6)
}

#endif /* UART_H_ */